config/routes.rb
RRProject::Application.routes.draw do

  devise_for :users
  devise_for :admins
  root 'pages#home'
  resources :users do #nests tasks by users
    resources :tasks
    resources :notifications
  end
  resources :tasks #standard tasks views
  resources :notifications

  get '/contact', :to => 'pages#contact'
  get '/about', :to => 'pages#about'
  get '/help', :to => 'pages#help'
  get '/signup', :to => 'users#new'
  get 'riorunner', :to => 'pages#riorunner'
  get '/users/sign_up', :to => 'devise/registrations#new'
  get '/posttask', :to => 'pages#posttask'
  get '/myriorunner/:id', :to => 'users#my_rio_runner', as: 'myriorunner'

  

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/notification.rb
class Notification < ActiveRecord::Base #ActiveRecord is what Rails use to talk to a Database.
  belongs_to :user
  #validates_presence_of
  default_scope order('created_at DESC') #Changes the Default Sort Order to (Created At.)
end

app/models/task.rb
class Task < ActiveRecord::Base #ActiveRecord is what Rails use to talk to a Database.
  belongs_to :user
  validates_presence_of :subject, :description, :zipcode
  default_scope order('created_at DESC') #Changes the Default Sort Order to (Created At.)
end

app/models/user.rb
class User < ActiveRecord::Base #ActiveRecord is what Rails use to talk to a Database.
# This sets it so the user can only edit their name and email.
# Will not allow id, created_at and update_at to be modified in any way.

# Include default devise modules. Others available are:
# :confirmable, :lockable, :timeoutable and :omniauthable
devise :database_authenticatable, :registerable,
       :recoverable, :rememberable, :trackable, :validatable

#required fields! email is being required someplace else though!
validates_presence_of :first_name, :last_name, :phone
validates :phone, length: {minimum: 7, maximum: 10}
before_save :uppercase_fields

def uppercase_fields
  self.first_name.capitalize!
  self.last_name.capitalize!
end
has_many :tasks
has_many :notifications
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :store_requested_url
  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:email, :password, :password_confirmation, :first_name, :last_name, :phone, :about_me) }
  end
  #this is overriding deviseregistrationcontroller for sign in path and going to the home page of the newly created user.
  def after_sign_in_path_for(resource)
    session[:requested_url] || myriorunner_path(@user) #<= see how you pass in the user to get the id....
  end
  #this is overriding deviseregistrationcontroller for sign out path
  #this is eventually going to want to go to root_path but for sake of testing it is going here..

  def after_sign_out_path_for(resource)
    root_path
  end
  private

  def store_requested_url
    #stores last url as long as its not in /users path
    session[:previous_url] = request.fullpath unless request.fullpath =~ /\/users/
  end

end

app/controllers/notifications_controller.rb
class TasksController < ApplicationController

  def index
    @notifications = Notification.all
  end

  def new
    @notifications = Notification.new
  end

  def show
    @notifications = Notification.find(params[:id])

  end

  def create
    @notifications = Notification.new(task_params)
    @notifications.user_id = current_user.id
  end
  def destroy
    @notifications = Notification.find(params[:id])
    @notifications.destroy
    if @notifications.destroy
      flash[:success] = "Task Deleted Correctly"
      redirect_to user_path(current_user.id)
    else
      flash.now[:error] = "Could not Delete Task"
      render 'new'
    end
  end

  private
  #def task_params
  #  params.require(:task).permit(:subject, :description, :deliverables, :duration, :price, :due_date)
  #end
  def task_params
    params.require(:task).permit(:user_id, :id, :subject, :description, :deliverables, :zipcode)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
    @title = "Home"
  end

  def about
    @title = "About"
  end

  def contact
    @title = "Contact"
  end

  def help
    @title = "Help"
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  before_filter :authenticate_user!

  def index
    @tasks = Task.all
  end

  def new
    @task = Task.new
  end

  def show
    @task = Task.find(params[:id])
  end

  def create
    @task = Task.new(task_params)
    @task.user_id = current_user.id
    if @task.save
      flash[:success] = "Task Posted Correctly"
      redirect_to myriorunner_path(current_user.id)
    else
      flash.now[:error] = "Could not save Task"
      render 'new'
    end
  end
  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    if @task.destroy
      flash[:success] = "Task Deleted Correctly"
      redirect_to user_path(current_user.id)
    else
      flash.now[:error] = "Could not Delete Task"
      render 'new'
    end
  end

  private
  #def task_params
  #  params.require(:task).permit(:subject, :description, :deliverables, :duration, :price, :due_date)
  #end
  def task_params
    params.require(:task).permit(:user_id, :id, :subject, :description, :deliverables, :zipcode)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all # getting all the users!
  end

  def new
    @user = User.new
  end

  def show
    @user = User.find(params[:id])
    @tasks = @user.tasks
  end
  def my_rio_runner
    @user = User.find(params[:id])
    @tasks = @user.tasks
    @notifications = @user.notifications
  end
  def create
    @user = User.new(params[:user]) # Not the final implementation!
    if @user.save
      flash[:success] = "User Created Successfully"
    else
      render 'new'
    end
  end

   private

   def user_params
   	params.require(:user).permit(:name, :first_name, :last_name, :email, :password, :password_confirmation, :about_me)
   end
end

app/helpers/application_helper.rb
module ApplicationHelper

  # Don't believe I need this page anymore!!!!
  #Return a title on a per-page basis...
  def title
    base_title = "RR Project - Coming Soon!!!"
    if @title.nil?
      base_title
    else
      "#{base_title} | #{@title}"
    end
  end
  def logo
    image_tag("RRMockLogo.png", :alt => "Logo Will Go Here", :class => "round")
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
  # Returns the Gravatar (http://gravatar.com/) for the given user.
  def gravatar_for(user)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end

  def show_mytasks_for(user)

  end

  def show_all_tasks

  end
end

app/views/layouts/_footer.html.erb
<div class="navbar-inverse">
  <div class="container">
    <ul>
      <li>login</li>
    </ul>
    <%= debug (params) if Rails.env.development? %>
  </div>
</div>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Twitter Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "danger" %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>

    <% if user_signed_in? %>
        <%=link_to 'Rio Runner', myriorunner_path(current_user.id), class: "navbar-brand" %>
    <% else %>
        <%=link_to 'Rio Runner', root_path, class: "navbar-brand" %>
    <% end %>
  </div>

  <!-- Collect the nav links, forms, and other content for toggling -->
  <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
    <ul class="nav navbar-nav navbar-right">
      <% if user_signed_in? %>
          <li class="dropdown">
            <a href="" class="dropdown-toggle" data-toggle="dropdown"><%= current_user.first_name %><% if current_user.notifications.count >= 1%>&nbsp;<span class="badge"><%=current_user.notifications.count%></span><% end %><b class="caret"></b></a>
            <ul class="dropdown-menu">
              <li><a href="<%= myriorunner_path(current_user.id)%>">My Rio Runner<% if current_user.notifications.count >= 1%>&nbsp;<span class="badge"><%=current_user.notifications.count%></span><% end %></a></li>
              <li><%= link_to('My Account', user_path(current_user.id)) %></li>
              <li><%= link_to('Account Settings', edit_user_registration_path) %></li>
              <li><a href="#">Something else here</a></li>
              <li><a href="#">first link in dropdown</a></li>
              <li><a href="#">second link in dropdown</a></li>
              <li><a href="#">third link in dropdown</a></li>
              <li class="divider"></li>
              <li> <%= link_to('Logout', destroy_user_session_path, :method => :delete) %></li>
            </ul>
          </li>
      <% else %>
          <li><a href = "#" data-toggle ="modal" data-target = "#myModal">Maybe a sign in modal?</a></li>
          <li><%= link_to('Login', new_user_session_path)%> </li>
          <li><%= link_to('Register', new_user_registration_path)  %> </li>
      <%end%>
      <li><%= link_to "Home", root_path, class: "active" %></li>
      <li><%= link_to "Help", help_path %></li>
    </ul>
  </div><!-- /.navbar-collapse -->
</nav>

app/views/layouts/_stylesheets.html.erb
<!--[if lt IE 9]>
<script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->
<%= stylesheet_link_tag 'screen', :media => 'screen' %>
<%= stylesheet_link_tag 'print', :media => 'print' %>
<!--[if lt IE 8]><%= stylesheet_link_tag 'ie' %><![endif]-->
<%= stylesheet_link_tag 'custom', :media => 'screen' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Rails Bootstrap" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Rails Bootstrap" %>">
    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>
      <header>
        <%= render 'layouts/navigation' %>
      </header>
      <main role="main">
        <%= render 'layouts/messages' %>
        <%= yield %>
      </main>
      <%= render 'layouts/footer' %>


      <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-dialog">
          <div class="modal-content">
            <div class="modal-header">
              <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
              <h4 class="modal-title" id="myModalLabel">Modal title</h4>
            </div>
            <div class="modal-body">
              <h2>Sign in</h2>


            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
              <button type="button" class="btn btn-primary">Save changes</button>
            </div>
          </div><!-- /.modal-content -->
        </div><!-- /.modal-dialog -->
      </div><!-- /.modal -->
      <script>
          $("tr[data-link]").click(function() {
              window.location = $(this).data("link")
          })
      </script>
  </body>
</html>

app/views/notifications/_notifications.html.erb
<h1>Listing Notifications</h1>

<% @user.notifications.each do |notification| %>
    <tr>
      <td><%= notification.todo %></td>
      <td><%= notification.description %></td>
      <td><%= notification.status %></td>
      <td><%= link_to "Remove", notification, method: :delete, data: { confirm: "Are you sure?" } %></td>
    </tr>
<% end %>

app/views/notifications/index.html.erb
<h1>Index!!!</h1>

app/views/pages/about.html.erb
<h2>About Us Page</h2>
<p>
  This will be the RR About Us Page.
</p>

app/views/pages/contact.html.erb
<h2>Contact Us Page</h2>
<p>
  This will be the RR Contact Us Page.
</p>

app/views/pages/help.html.erb
<h2>Help Page</h2>
<p>
  This will be the RR Help Page.
</p>

app/views/tasks/index.html.erb
<h1>View All Current Tasks</h1>
<div class =  "row" id = "tasks">
  <div class = "col-md-12">
    <table class = "table table-bordered table-hover">
      <thead>
      <tr>
        <th>Status</th>
        <th>Subject</th>
        <th>Description</th>
        <th>Zip Code</th>
        <th>Deliverables</th>
      </tr>
      </thead>
      <tbody>
      <% Task.all.each do |task| %>
          <tr data-link = "<%=user_task_path(current_user.id, task.id)%>" class ="row_hover">
            <td></td>
            <td><%= task.subject %></td>
            <td><%= task.description %></td>
            <td><%= task.zipcode %></td>
            <td><%= task.deliverables %></td>
          </tr>
      <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/tasks/new.html.erb
<% flash.each do |name, msg| -%>
    <%= content_tag :div, msg, class: "round alert label" %>
<% end -%>
<h1>Create Task</h1>

<div class="row">
  <div class="span6 offset3">

    <!--  The presence of the do keyword indicates that form_for takes a block with one variable, which we’ve called f for “form”: -->
    <%= form_for(@task) do |f| %>
        <!-- As is usually the case with Rails helpers, we don’t need to know any details about the implementation,
        but what we do need to know is what the f object does: when called with a method corresponding to an HTML form element—such as a text field,
        radio button, or password field—it returns code for that element specifically designed to set an attribute of the @user object.
        In other words, creates the HTML needed to make a labeled text field element appropriate for setting the name attribute of a User model. -->

        <%= f.label :subject, "Subject" %>
        <%= f.text_field :subject %>

        <%= f.label :description, "Description" %>
        <%= f.text_field :description %>

        <%= f.label :zipcode %>
        <%= f.text_field :zipcode %>

        <%= f.label :deliverables %>
        <%= f.text_field :deliverables %>

        <%= f.submit "Submit Task", class: "button" %>

    <% end %>
  </div>
</div>

app/views/tasks/show.html.erb
<% provide(:title, @task.description) %>
<!--classes row and span4 are apart of bootstrap-->
<div class="row">
  <div class="col-md-8 center">
    <section>
      <h1>
        Subject: <%= @task.subject %> <br />
        Description: <%= @task.description %> <!--What happens to this line when I change name to firstname & lastname?-->
      </h1>
      <% if current_user.id == @task.user_id %>
          <%= link_to 'Destroy', {:controller=>:tasks,:action=>:destroy, :id=>@task},:data => { :confirm => "Are you sure?" }, :method=>:delete %>
      <% end %>
    </section>
  </div>
</div>

app/views/users/_fields.html.erb
<div class="field">
  <%= f.label :name %><br />
  <%= f.text_field :name %>
</div>
<div class="field">
  <%= f.label :email %><br />
  <%= f.text_field :email %>
</div>
<div class="field">
  <%= f.label :password %><br />
  <%= f.password_field :password %>
</div>
<div class="field">
  <%= f.label :password_confirmation, "Confirmation" %><br />
  <%= f.password_field :password_confirmation %>
</div>

app/views/users/_notifications.html.erb
<h1>Listing Notifications</h1>

<% @user.notifications.each do |notification| %>
    <tr>
      <td><%= notification.todo %></td>
      <td><%= notification.description %></td>
      <td><%= notification.status %></td>
      <td><%= link_to "Remove", notification, method: :delete, data: { confirm: "Are you sure?" } %></td>
    </tr>
<% end %>

app/views/users/index.html.erb
<h1>I guess it wants an index....</h1>

app/views/users/my_rio_runner.html.erb
<div class="row">
  <div class = "col-md-6 pull-left text-center">
  <H1>My Rio Runner</H1>
  <%= link_to 'See Public Profile', user_path(@user.id), class: "btn btn-primary" %><br /><br />
  <%= gravatar_for @user %> <!--This will pull the usx`ers gravatar using their email address...users_helper.rb-->
  <h1 class = "text-center">
    Hello, <%= @user.first_name %> <!--What happens to this line when I change name to firstname & lastname?-->
  </h1>
  <br />
  <h4><%= @user.about_me %></h4>
  <br />
  </div>
  <div class = "col-md-6 pull-right text-center panel panel-danger">
    <h1>Listing Notifications</h1>

    <% @user.notifications.each do |notification| %>
        <tr>
          <td><%= notification.description %></td>
          <td><%= link_to "Remove", notification, method: :delete, data: { confirm: "Are you sure?" } %></td>
        </tr>
    <% end %>
  </div>
</div>
<div class = "row">

  <div class = "col-md-6 pull-left">
    <h3>My Tasks</h3>

    <% if @user.tasks.empty? %>
        <h4>This user has not posted any tasks...</h4>
    <% else %>

        <table class = "table table-bordered table-hover">
          <thead>
          <tr>
            <th>Status</th>
            <th>Subject</th>
            <th>Description</th>
            <th>Zip Code</th>
            <th>Deliverables</th>
          </tr>
          </thead>
          <tbody>
          <% @user.tasks.take(5).each do |task| %>
              <tr data-link = "<%=user_task_path(current_user.id, task.id)%>" class ="row_hover">
                <td><%= link_to 'view task', user_task_path(current_user.id, task.id) %></td>
                <td><%= task.subject %></td>
                <td><%= task.description %></td>
                <td><%= task.zipcode %></td>
                <td><%= task.deliverables %></td>
              </tr>
          <% end %>
          </tbody>
        </table>
    <% end %>
    <% if @user.tasks.count > 5 %>
        <a href ="#" class = "pull-right">View All My Tasks</a>
    <% end %>
    <%= link_to 'Post a Task', new_user_task_path(current_user.id), class: "btn btn-primary pull-left"%>
  </div>


  <div class = "col-md-6 pull-right">
    <h3>All Current Tasks</h3>
    <table class = "table table-bordered table-hover">
      <thead>
      <tr>
        <th>Status</th>
        <th>Subject</th>
        <th>Description</th>
        <th>Zip Code</th>
        <th>Deliverables</th>
      </tr>
      </thead>
      <tbody>
      <% Task.order('subject').take(5).each do |task| %>
          <tr data-link = "<%=user_task_path(current_user.id, task.id)%>" class ="row_hover">
            <td><span class ="glyphicon glyphicon-credit-card text-center"></span></td>
            <td><%= task.subject %></td>
            <td><%= task.description %></td>
            <td><%= task.zipcode %></td>
            <td><%= task.deliverables %></td>
          </tr>
      <% end %>
      </tbody>
    </table>

    <% if Task.count > 5 %>
        <%= link_to 'List all Tasks' , tasks_path%>
    <% end %>
  </div>
</div>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>

<h1>Sign up</h1>

<div class="row">
  <div class="span6 offset3">
<!--  The presence of the do keyword indicates that form_for takes a block with one variable, which we’ve called f for “form”: -->
    <%= form_for(@user) do |f| %>
      <%= render 'users/shared/error_messages' %>
<!-- As is usually the case with Rails helpers, we don’t need to know any details about the implementation,
but what we do need to know is what the f object does: when called with a method corresponding to an HTML form element—such as a text field,
radio button, or password field—it returns code for that element specifically designed to set an attribute of the @user object.
In other words, creates the HTML needed to make a labeled text field element appropriate for setting the name attribute of a User model. -->
      <%= f.label :name, "Name" %>
      <%= f.text_field :name %>

      <%= f.label :email %>
      <%= f.text_field :email %>

      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "Confirm Password" %>
      <%= f.password_field :password_confirmation %>

      <%= f.submit "Start Running", class: "btn btn-large btn-primary" %>

    <% end %>
  </div>
</div>

<!--
 	<	%= f.label :name %>
    <	%= f.text_field :name %>
    ....produces....
  <label for="user_name">Name</label>
  <input id="user_name" name="user[name]" type="text" />

  <label for="user_email">Email</label>
  <input id="user_email" name="user[email]" type="text" />

  <label for="user_password">Password</label>
  <input id="user_password" name="user[password]"
         type="password" />

  <label for="user_password_confirmation">Confirmation</label>
  <input id="user_password_confirmation"
         name="user[password_confirmation]" type="password" />

  <input class="btn btn-large btn-primary" name="commit" type="submit"
         value="Create my account" />
</form>
-->

app/views/users/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Sign in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  New User? <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/users/show.html.erb
<h1>External Show Page..</h1>

<div class="row">
  <div class = "col-md-12">
  <%= gravatar_for @user %> <!--This will pull the usx`ers gravatar using their email address...users_helper.rb-->
  <h1 class = "text-center">
    <%= @user.first_name%> <%=  @user.last_name.first[0,1] %>. <!--What happens to this line when I change name to firstname & lastname?-->
  </h1>
  <br />
  <h4><%= @user.about_me %></h4>
  <br />
  </div>
</div>